### ISSUE TITLE
Demonstração de abas

### ISSUE THREAD

**Issue by ronniery** [AdrianoLupossa/neptuno#2]
O primeiro item de demonstração das abas (lado esquerdo) não está respeitando a borda do filho quando e realizado o hover sobre a primeira aba.

![sem titulo](https://user-images.githubusercontent.com/5189503/50921363-0156e080-142f-11e9-90bf-04f8cbf6fc4c.png)

**Comment by AdrianoLupossa** [comment]
Resolvido!!
<a href="https://adrianolupossa.github.io/neptuno/dist/docs/tabs">Tabs</a>
